name: hello-world
on: push
jobs:
  my-job:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./proj
    steps:
      - uses: actions/checkout@v3
      - name: my-step
        uses: actions/checkout@v3
      - name: Compile
        run: |
          pwd
          g++ *.cpp
          ./a.out
          ifconfig
          
