name: hello-world
on: push
jobs:
  my-job:
    runs-on: [my_runner, label_practice]
    defaults:
      run:
        working-directory: ./proj
    strategy:
      matrix:
        gversion: [9.3.0]
    steps:
      - uses: actions/checkout@v3
      - name: my-step
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential
      - name: Compile
        run: |
          pwd
          g++ *.cpp
          ./a.out
          ifonfig
          
