name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./proj
    strategy:
      matrix:
        gversion: [9.3.0]
    steps:
      - uses: actions/checkout@v3
      - name: my-step
       # uses: actions/setup-g++@v9
        with:
          gversion: '${{matrix.gversion}}'
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential
          g++ ./proj/*.cpp
