name: hello-world
'on':
  pull_request:
    branches:
      - trial*
jobs:
  my-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./proj
    strategy:
      matrix:
        g++-version:
          - 9.3.0
    env:
      MODE: dev
    steps:
      - uses: actions/checkout@v3
      - name: my-step
        uses: actions/setup-g++@v9
        with:
          g++-version: '${{matrix.g++-version}}'
      - name: Install dependencies
    run: |
      sudo apt update
      sudo apt install build-essential

      - name: Testing app
          run: |
              g++ ./proj/*.cpp
              g++ ./a.out
